name = "CPLEXCP"
uuid = "cf5b58c4-1b5d-4a07-a0a4-f2f6c3ca5a5f"
authors = ["Thibaut Cuvelier <cuvelier.thibaut@gmail.com>"]
repo = "https://github.com/dourouc05/CPLEXCP.jl"
version = "0.1.0"

[deps]
JavaCall = "494afd89-becb-516b-aafa-70d2670c0337"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"
MathOptInterface = "^0.9"
JavaCall = "^0.7.4"
